package com.example.wecharades.model.test;

import org.junit.runner.JUnitCore;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import com.example.wecharades.model.test.AutoGeneratedDatabaseTest;

/**
 * The class <code>TestAll</code> builds a suite that can be used to run all
 * of the tests within its package as well as within any subpackages of its
 * package.
 *
 * @generatedBy CodePro at 2013-05-29 09:29
 * @author felixkarlsson
 * @version $Revision: 1.0 $
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
	InvitationTest.class,
	TurnTest.class,
	DBMessageTest.class,
	PlayerTest.class,
	LoadProgressBarTest.class,
	DataControllerTest.class,
	GameTest.class,
	RefreshProgressBarTest.class,
	IDatabaseTest.class,
	IProgressTest.class,
	DCMessageTest.class,
	DatabaseConverterTest.class,
	DatabaseExceptionTest.class,
})
public class TestAll {

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 2013-05-29 09:29
	 */
	public static void main(String[] args) {
		JUnitCore.runClasses(new Class[] { TestAll.class });
	}
}
